# config.yaml

path :
  root : "nerf_example_data/nerf_synthetic/lego"
  train : "nerf_example_data/nerf_synthetic/lego/train"
  val : "nerf_example_data/nerf_synthetic/lego/val"
  test : "nerf_example_data/nerf_synthetic/lego/test"
  outputs : "outputs"

data :
  img_size : 100
  train_size: 100
  val_size: 1

experiment :
  name : "lego"

model : 
  type: "nerf"
  depth: 9
  L_frequency_encoding: 6
  n_neurons: 256

train :
  batch_rays : 1024
  epoch: 1000
  log_every: 50
  lr : 1e-4
  N_samples : 32
  device : cpu
  near : 2.0
  far : 6.0

render :
  model_name: "lego_2025-10-03-10-48_nerf_weights"
  phi:  30.0
  theta: 60.0
  radius: 4.0
  step : 5

